-- number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key
-- foreign key () references ()

drop table detallePostulante;
drop table estado;
drop table expediente;
drop table postulante;
drop table detalleReq;
drop table requisito;
drop table detalleCat;
drop table categoria;
drop table detallePuesto;
drop table puesto;
drop table detalleRevisor;
drop table departamento;
drop table usuario;
drop table rol;

create table rol(
    idRol number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
    nombre varchar(100)
);

create table usuario(
    idUsuario number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
    fk_idRol number,
    nombre varchar(100) unique,
    contra varchar(100),
    fechaInicio date,
    fechaBaja date,
    debaja number,
    foreign key (fk_idRol) references rol(idRol)
);

create table departamento(
    idDep number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
    fk_idDepPadre number, 
    fk_idUsuario number unique,
    nombre varchar (100),
    capitalTotal number,
    capitalDisp number,
    foreign key (fk_idDepPadre) references departamento (idDep),
    foreign key (fk_idUsuario) references usuario (idUsuario)
);

create table detalleRevisor(
    fk_idUsario number primary key,
    fk_idDep number,
    foreign key (fk_idUsario) references usuario (idUsuario),
    foreign key (fk_idDep) references departamento (idDep)
);

create table puesto(
    idPuesto number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
    nombre varchar (100),
    salario number,
    urlImg varchar(300),
    descrip varchar (200)
);

create table detallePuesto(
    fk_idPuesto number, 
    fk_IdDep number,
    primary key (fk_idPuesto, fk_IdDep),
    foreign key (fk_idPuesto) references puesto(idPuesto),
    foreign key (fk_IdDep) references departamento (idDep)
);

create table categoria(
    idCat number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
    nombre varchar(100)
);

create table detalleCat(
    fk_idCat number,
    fk_idPuesto number,
    primary key (fk_idCat, fk_idPuesto), 
    foreign key (fk_IdCat) references categoria (idCat),
    foreign key (fk_idPuesto) references puesto(idPuesto)
);

create table requisito(
    idReq number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
    nombre varchar (100),
    tamaño number,
    obligatorio number,
    formato varchar(50)
);

create table detalleReq(
    fk_idReq number,
    fk_idPuesto number,
    primary key (fk_idReq, fk_idPuesto),
    foreign key (fk_idReq) references requisito (idReq),
    foreign key (fk_idPuesto) references puesto(idPuesto)
);

create table postulante(
    dpi number primary key,
    nombre varchar (100),
    apellido varchar (100),
    email varchar (100),
    direccion varchar (100),
    tel number,
    urlCV varchar(300)
);

create table expediente(
    fk_dpi number,
    fk_idReq number,
    urlReq varchar(250),
    aprobado varchar(1),
    descrip varchar (200),
    primary key (fk_dpi, fk_idReq),
    foreign key (fk_dpi) references postulante(dpi),
    foreign key (fk_idReq) references requisito (idReq)
);

create table estado(
    idEstado number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
    nombreEstado varchar(50)
);

create table detallePostulante(
    fk_dpi number primary key,
    fk_idEstado number,
    fk_idUsario_dp number,
    fk_idDep_dp number,
    fk_idPuesto_dp number,
    fechaPostulacion date,
    fechaContratacion date,
    foreign key (fk_dpi) references postulante (dpi),
    foreign key (fk_idEstado) references estado (idEstado),
    foreign key (fk_idUsario_dp) references detalleRevisor (fk_idUsario),
    foreign key (fk_idDep_dp, fk_idPuesto_dp) references detallePuesto (fk_IdDep, fk_idPuesto)
);

---------------------------------------Insercciones varias-----------------------------------------------------------------

insert into rol (nombre) values('admin');
insert into rol (nombre) values('coordinador');
insert into rol (nombre) values('reclutador');
insert into rol (nombre) values('aplicante');

select * from rol;

insert into usuario(fk_idRol, nombre, contra, fechaInicio, debaja) values (1, 'davi', '1234', (Select sysdate from dual), 0);
insert into usuario(fk_idRol, nombre, contra, fechaInicio, debaja) values (2, 'maxi', '321', (Select sysdate from dual), 0);
insert into usuario(fk_idRol, nombre, contra, fechaInicio, debaja) values (2, 'loli', '1234', (Select sysdate from dual), 0);
insert into usuario(fk_idRol, nombre, contra, fechaInicio, debaja) values (3, 'cloe', '321', (Select sysdate from dual), 0);
insert into usuario(fk_idRol, nombre, contra, fechaInicio, debaja) values (4, 'lia', '1234', (Select sysdate from dual), 0);

select * from usuario;
------------------------------------------carga Masiva----------------------------------------------------------

select * from departamento;

select * from puesto;

select * from categoria;

select * from requisito;































